#pragma once
#include "TypeMeta.h"
#include "SceneComponents.h"

namespace won::reflection
{
    WON_REFLECT_SCALAR(bool, "bool", won::ValueType::Bool)

    WON_REFLECT_SCALAR(won::int8, "int8", won::ValueType::Int8)
    WON_REFLECT_SCALAR(won::uint8, "uint8", won::ValueType::UInt8)
    WON_REFLECT_SCALAR(won::int16, "int16", won::ValueType::Int16)
    WON_REFLECT_SCALAR(won::uint16, "uint16", won::ValueType::UInt16)
    WON_REFLECT_SCALAR(won::int32, "int32", won::ValueType::Int32)
    WON_REFLECT_SCALAR(won::uint32, "uint32", won::ValueType::UInt32)
    WON_REFLECT_SCALAR(won::int64, "int64", won::ValueType::Int64)
    WON_REFLECT_SCALAR(won::uint64, "uint64", won::ValueType::UInt64)
    WON_REFLECT_SCALAR(float, "float", won::ValueType::Float32)
    WON_REFLECT_SCALAR(double, "double", won::ValueType::Float64)
    WON_REFLECT_SCALAR(void*, "Pointer", won::ValueType::Pointer)
    WON_REFLECT_SCALAR(won::String, "String", won::ValueType::String)

    WON_REFLECT_BUILTIN_STRUCT(float2, "float2", won::ValueType::Float32x2)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(float3, "float3", won::ValueType::Float32x3)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(float4, "float4", won::ValueType::Float32x4)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(w, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(int2, "int2", won::ValueType::Int32x2)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(int3, "int3", won::ValueType::Int32x3)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(int4, "int4", won::ValueType::Int32x4)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(w, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(uint2, "uint2", won::ValueType::UInt32x2)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(uint3, "uint3", won::ValueType::UInt32x3)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_BUILTIN_STRUCT(uint4, "uint4", won::ValueType::UInt32x4)
        WON_REFLECT_FIELD(x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(z, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(w, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_ENUM(won::ecs::LightComponent::LightType, "LightType")
        WON_REFLECT_ENUM_VALUE("Directional", won::ecs::LightComponent::LightType::Directional)
        WON_REFLECT_ENUM_VALUE("Point", won::ecs::LightComponent::LightType::Point)
        WON_REFLECT_ENUM_VALUE("Spot", won::ecs::LightComponent::LightType::Spot)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::EnvironmentComponent::DiffuseGIMode, "DiffuseGIMode")
        WON_REFLECT_ENUM_VALUE("None", won::ecs::EnvironmentComponent::DiffuseGIMode::None)
        WON_REFLECT_ENUM_VALUE("Ambient", won::ecs::EnvironmentComponent::DiffuseGIMode::Ambient)
        WON_REFLECT_ENUM_VALUE("DDGI", won::ecs::EnvironmentComponent::DiffuseGIMode::DDGI)
        WON_REFLECT_ENUM_VALUE("Cubemap", won::ecs::EnvironmentComponent::DiffuseGIMode::Cubemap)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::EnvironmentComponent::ReflectionMode, "ReflectionMode")
        WON_REFLECT_ENUM_VALUE("None", won::ecs::EnvironmentComponent::ReflectionMode::None)
        WON_REFLECT_ENUM_VALUE("Cubemap", won::ecs::EnvironmentComponent::ReflectionMode::Cubemap)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::EnvironmentComponent::SkyType, "SkyType")
        WON_REFLECT_ENUM_VALUE("None", won::ecs::EnvironmentComponent::SkyType::None)
        WON_REFLECT_ENUM_VALUE("Procedural", won::ecs::EnvironmentComponent::SkyType::Procedural)
        WON_REFLECT_ENUM_VALUE("Cubemap", won::ecs::EnvironmentComponent::SkyType::Cubemap)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::Collider3DComponent::ShapeType, "Collider3DShapeType")
        WON_REFLECT_ENUM_VALUE("Box", won::ecs::Collider3DComponent::ShapeType::Box)
        WON_REFLECT_ENUM_VALUE("Sphere", won::ecs::Collider3DComponent::ShapeType::Sphere)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::UIScaleMode, "UIScaleMode")
        WON_REFLECT_ENUM_VALUE("ConstantPixelSize", won::ecs::UIScaleMode::ConstantPixelSize)
        WON_REFLECT_ENUM_VALUE("ScaleWithScreenSize", won::ecs::UIScaleMode::ScaleWithScreenSize)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::Canvas2DComponent::RenderMode, "Canvas2DRenderMode")
        WON_REFLECT_ENUM_VALUE("ScreenOverlay", won::ecs::Canvas2DComponent::RenderMode::ScreenOverlay)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::Rigidbody3DComponent::MotionType, "Rigidbody3DMotionType")
        WON_REFLECT_ENUM_VALUE("Static", won::ecs::Rigidbody3DComponent::MotionType::Static)
        WON_REFLECT_ENUM_VALUE("Kinematic", won::ecs::Rigidbody3DComponent::MotionType::Kinematic)
        WON_REFLECT_ENUM_VALUE("Dynamic", won::ecs::Rigidbody3DComponent::MotionType::Dynamic)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::JointComponent::JointType, "JointType")
        WON_REFLECT_ENUM_VALUE("Fixed", won::ecs::JointComponent::JointType::Fixed)
        WON_REFLECT_ENUM_VALUE("Hinge", won::ecs::JointComponent::JointType::Hinge)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_STRUCT(won::ecs::NameComponent, "NameComponent")
        WON_REFLECT_FIELD(value, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::TransformComponent, "TransformComponent")
        WON_REFLECT_FIELD(position, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(rotation, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(scale, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::HierarchyComponent, "HierarchyComponent")
        WON_REFLECT_FIELD(parent_id, won::FieldFlagEditable | won::FieldFlagSerializable | won::FieldFlagEntityRef)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::CameraComponent, "CameraComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(near_plane, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(far_plane, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(aspect_ratio, won::FieldFlagNone)
        WON_REFLECT_FIELD(fov_y, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ortho_vertical_size, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(aperture, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shutter_speed, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sensitivity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(exposure_compensation, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(auto_exposure_speed, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(auto_exposure_min_ev, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(auto_exposure_max_ev, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(culling_mask, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::LightComponent, "LightComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(range, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(outer_cone_angle, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(inner_cone_angle, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shadow_map_resolution, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shadow_cascade_count, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shadow_cascade_lambda, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shadow_cascade_blend, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::EnvironmentComponent, "EnvironmentComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(diffuse_gi_mode, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(reflection_mode, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_direction, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_angular_radius, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_glow_intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sun_glow_falloff, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_horizon_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_zenith_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_horizon_falloff, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ground_horizon_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ground_intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ground_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ground_falloff, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ambient_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ambient_intensity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(turbidity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(mie_eccentricity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(rayleigh_coefficient, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(mie_coefficient, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_active, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_cast_shadow, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_shadow_resolution, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_cascade_count, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_cascade_lambda, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(direct_sun_cascade_blend, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(indirect_diffuse_scale, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(indirect_specular_scale, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sky_cubemap_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(irradiance_cubemap_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(specular_cubemap_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::FogVolumeComponent, "FogVolumeComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::DDGIVolumeComponent, "DDGIVolumeComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(probe_counts, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(probe_spacing, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(volume_offset, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(probes_per_frame, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(priority, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(hysteresis, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(normal_bias, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(view_bias, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(max_distance, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::ReflectionProbeComponent, "ReflectionProbeComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(cubemap_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(influence_radius, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(intensity_multiplier, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::GeometryComponent, "GeometryComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(mesh_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Sprite2DComponent, "Sprite2DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(uv_rect, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(layer, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Canvas2DComponent, "Canvas2DComponent")
        WON_REFLECT_FIELD(render_mode, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(scale_mode, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(reference_resolution, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sort_order, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(layer_mask, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(match, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::RectTransform2DComponent, "RectTransform2DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(anchor, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(position, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(size, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pivot, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::ButtonComponent, "ButtonComponent")
        WON_REFLECT_FIELD(enabled, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::LayoutComponent, "LayoutComponent")
        WON_REFLECT_FIELD(type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(padding_min, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(padding_max, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(spacing, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(cross_align, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(reverse, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Sprite3DComponent, "Sprite3DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(size, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pivot, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(uv_rect, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Text2DComponent, "Text2DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(font_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(text, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(text_key, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pixel_height, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(layer, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Text3DComponent, "Text3DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(font_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(text, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(text_key, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pixel_height, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(height, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pivot, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AnimationComponent, "AnimationComponent")
        WON_REFLECT_FIELD(current_clip_index, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(time, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(speed, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(loop, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(playing, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_ENUM(won::ecs::AnimationParameter::Type, "AnimationParameterType")
        WON_REFLECT_ENUM_VALUE("Bool", won::ecs::AnimationParameter::Type::Bool)
        WON_REFLECT_ENUM_VALUE("Float", won::ecs::AnimationParameter::Type::Float)
        WON_REFLECT_ENUM_VALUE("Trigger", won::ecs::AnimationParameter::Type::Trigger)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::ecs::TransitionCondition::Op, "TransitionConditionOp")
        WON_REFLECT_ENUM_VALUE("Greater", won::ecs::TransitionCondition::Op::Greater)
        WON_REFLECT_ENUM_VALUE("Less", won::ecs::TransitionCondition::Op::Less)
        WON_REFLECT_ENUM_VALUE("Equal", won::ecs::TransitionCondition::Op::Equal)
        WON_REFLECT_ENUM_VALUE("NotEqual", won::ecs::TransitionCondition::Op::NotEqual)
        WON_REFLECT_ENUM_VALUE("IsTrue", won::ecs::TransitionCondition::Op::IsTrue)
        WON_REFLECT_ENUM_VALUE("IsFalse", won::ecs::TransitionCondition::Op::IsFalse)
        WON_REFLECT_ENUM_VALUE("TriggerSet", won::ecs::TransitionCondition::Op::TriggerSet)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_STRUCT(won::ecs::AnimationState, "AnimationState")
        WON_REFLECT_FIELD(name, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(clip, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(loop, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(speed, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AnimationParameter, "AnimationParameter")
        WON_REFLECT_FIELD(name, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(value, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::TransitionCondition, "TransitionCondition")
        WON_REFLECT_FIELD(parameter, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(op, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(threshold, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AnimationTransition, "AnimationTransition")
        WON_REFLECT_FIELD(from_state, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(to_state, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(blend_duration, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(has_exit_time, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(exit_time, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(conditions, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AnimationStateMachineComponent, "AnimationStateMachineComponent")
        WON_REFLECT_FIELD(states, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(parameters, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(transitions, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(default_state, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Collider3DComponent, "Collider3DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(shape_type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(offset, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(half_extent, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(radius, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(friction, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(restitution, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::Rigidbody3DComponent, "Rigidbody3DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(motion_type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(mass, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(gravity_factor, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(linear_velocity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(angular_velocity, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::JointComponent, "JointComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(type, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(connected_entity, won::FieldFlagEditable | won::FieldFlagSerializable | won::FieldFlagEntityRef)
        WON_REFLECT_FIELD(anchor, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(axis, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(use_limit, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(limit_min, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(limit_max, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::BehaviorTreeComponent, "BehaviorTreeComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(tree_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::NavAgentComponent, "NavAgentComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(move_speed, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(arrival_threshold, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(turn_rate, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AudioSourceComponent, "AudioSourceComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sound_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(volume, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(pitch, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(min_distance, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(max_distance, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(submix, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::AudioListenerComponent, "AudioListenerComponent")
        WON_REFLECT_FIELD(enabled, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::VisibilityLayerComponent, "VisibilityLayerComponent")
        WON_REFLECT_FIELD(layer_mask, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::CollisionLayerComponent, "CollisionLayerComponent")
        WON_REFLECT_FIELD(layer, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::TerrainComponent, "TerrainComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(resolution_x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(resolution_z, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(world_size_x, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(world_size_z, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(height_scale, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(seed, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(frequency, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(octaves, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(lacunarity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(persistence, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(ridge_strength, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(warp_strength, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(island_falloff, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::NavMeshComponent, "NavMeshComponent")
        WON_REFLECT_FIELD(agent_radius, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(agent_height, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(agent_max_climb, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(agent_max_slope, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(use_bounds, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(bounds_center, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(bounds_extent, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(include_layers, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(navmesh_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::ParticleEmitter3DComponent, "ParticleEmitter3DComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(max_particle_count, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(spawn_rate, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(lifetime, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(start_size, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(end_size, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(start_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(end_color, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(velocity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(velocity_variation, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(gravity, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(emit_radius, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(seed, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::DecalComponent, "DecalComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_ENUM(won::resource::MaterialType, "MaterialType")
        WON_REFLECT_ENUM_VALUE("Unlit", won::resource::MaterialType::Unlit)
        WON_REFLECT_ENUM_VALUE("PBR", won::resource::MaterialType::PBR)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_ENUM(won::resource::MaterialBlendMode, "MaterialBlendMode")
        WON_REFLECT_ENUM_VALUE("Opaque", won::resource::MaterialBlendMode::Opaque)
        WON_REFLECT_ENUM_VALUE("Masked", won::resource::MaterialBlendMode::Masked)
        WON_REFLECT_ENUM_VALUE("Transparent", won::resource::MaterialBlendMode::Transparent)
        WON_REFLECT_ENUM_VALUE("Additive", won::resource::MaterialBlendMode::Additive)
        WON_REFLECT_ENUM_VALUE("Premultiplied", won::resource::MaterialBlendMode::Premultiplied)
    WON_REFLECT_ENUM_END()

    WON_REFLECT_STRUCT(won::resource::MaterialSlot::TextureMap, "TextureMap")
        WON_REFLECT_FIELD(texture_asset_path, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::resource::MaterialSlot, "MaterialSlot")
        WON_REFLECT_FIELD(material_type, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(blend_mode, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(double_sided, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(use_vertex_colors, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(receive_shadow, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(base_color, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(metallic, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(roughness, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(reflectance, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(anisotropy, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sheen_color, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(sheen_roughness, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(clearcoat, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(clearcoat_roughness, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(textures, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::MaterialComponent, "MaterialComponent")
        WON_REFLECT_FIELD(flags, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(material_asset_path, won::FieldFlagEditable | won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::ScriptSlot, "ScriptSlot")
        WON_REFLECT_FIELD(script_path, won::FieldFlagSerializable)
        WON_REFLECT_FIELD(enabled, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()

    WON_REFLECT_STRUCT(won::ecs::ScriptComponent, "ScriptComponent")
        WON_REFLECT_FIELD(enabled, won::FieldFlagEditable | won::FieldFlagSerializable)
        WON_REFLECT_FIELD(scripts, won::FieldFlagSerializable)
    WON_REFLECT_STRUCT_END()
}
