#pragma once

#include "TransformUpdateSystem.h"
#include "PhysicsUpdateSystem.h"
#include "CameraUpdateSystem.h"
#include "LightUpdateSystem.h"
#include "AnimationUpdateSystem.h"
#include "AnimationStateMachineSystem.h"
#include "BehaviorTreeSystem.h"
#include "NavAgentSystem.h"
#include "SequenceSystem.h"
#include "MeshUpdateSystem.h"
#include "ParticleUpdateSystem.h"
#include "WaterSimulationSystem.h"
#include "ScriptUpdateSystem.h"
#include "ScriptEventDispatchSystem.h"
#include "AudioUpdateSystem.h"
#include "LocalizeTextSystem.h"
